name: CI & CD
on:
  push:
    branches:
      - hexo
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install & Build
        run: pnpm i  &&  pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          cname: fcc-cd.dev
          publish_branch: master
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
